### PR TITLE
WIP: Add specializ(ed/able) RWs

### PR DESCRIPTION
**Pull request by jcorbin**
## This PR is not to be merged, it tracks each of the components as I test and merge them separately:

- [x] boolean semantics on a unsigned byte
- [x] statically typed list (with fixed width optimization)
- [ ] statically typed map (with kay/val fixed width optimizations)
  - [x] as Object
  - [x] as Entries
  - [ ] as Map
- [ ] statically typed struct
- [ ] statically typed union

cc @kriskowal @leizha

### CODE REVIEW

**Comment by jcorbin** [comment]
The idea is that this layer can replace the entire uglify/reify `A*` layer of thriftify, leaving it to care only about parsing and scope concerns.

**Comment by jcorbin** [comment]
I'll be breaking this out into separate PRs, keeping this branch around for integration testing, and this PR open until all of its components are merged.

**Comment by kriskowal** [comment]
Hey, @jcorbin, I made some progress on this, working from the Thrift IDL parser down, where this is working from the bottom up. In #15, I met you in the middle. In that WIP, there’s some overlap here, but it’s toward the same result. I’m getting @malandrew boot-strapped on this project by consolidating and decomposing this WIP and the #15 WIP.

To begin, I shaved off #16 (base type RWs and Specs) and @malandrew is getting that branch up to our coverage standard now. In the end, we’ll have a Spec constructor that is interface-compatible and feature-parity+ with Thriftify. Again, mapped this out on #15. I’m picking up MapSpec and statically typed StructSpec. That leaves Union stranded here.

**Comment by s-panferov** [comment]
@kriskowal hello, could you describe your current plans on that PR? We want to start using the library and make some enchantments to support `import`, but we don't understand, which library/branch we should use.

**Comment by jcorbin** [comment]
Pretty sure it's all done now on master, @kriskowal can correct if anything is still outstanding.

**Pull request closed without merging**
