### PR TITLE
Thrift Exceptions aren't actually exceptional

### PR DESCRIPTION
**Pull request by kriskowal**
Thrift exceptions aren’t actually exceptional. The stack trace is useless and hinders performance, so why even. We don’t need to know that the exception was created in the RW path, and we never throw the ones we make ourselves.

DISCUSS

@jakev @malandrew @jcorbin

### CODE REVIEW

**Comment by malandrew** [comment]
Completely in agreement on this. If stack traces aren't useful, there really isn't a use in having them. So long as we have some string identifier that can be grepped for in the source to know where the exception was generated that is good enough for me (b/c such a thing can be useful in case there is a bug in thriftrw)

On the other hand, exceptions should be an exception (i.e. rare), so optimizing them for performance seems unnecessary.

**Comment by Raynos** [comment]
Yep.

Thrift exceptions are just objects. In the client it should be an object; not an instanceof error.

In the server when sending an exception we should take an error or an object.

**Comment by Raynos** [comment]
@malandrew 

Thrift exceptions are not rare. Write code that scales with errors. Performance is performance.

**Comment by Willyham** [comment]
Not that I'm arguing against this change, nor am I arguing that this change would not increse performance, but I would like to see us back up any performance improvements with real data from a service in production (even if it is a stooge).

**Comment by Raynos** [comment]
This happened in hyperbahn. We changed error frames to be objects instead of instances of error and got a 20% speed up.

Same thing applies to thriftrw

**Pull request merged**
