### PR TITLE
Add support for Long representation of i64

### LINKED ISSUE #68: better i64 support
These should be returned using a bigint type or something. DISCUSS

### PR DESCRIPTION
**Pull request by kriskowal**
Fixes #68

### CODE REVIEW

**Comment by kriskowal** [comment]
r @malandrew 
cc @Raynos @blampe

**Comment by Raynos** [comment]
noice.

**Comment by malandrew** [comment]
lgtm. shipit.

**Comment by blampe** [comment]
YOU ARE SO COOL

**Pull request merged**
